### PR TITLE
[#9] Spring Cloud Kubernetes produces NullPointerException for ServiceInstance#getMetaData

### LINKED ISSUE #9: Spring Cloud Kubernetes produces NullPointerException for ServiceInstance#getMetaData
I'm trying to switch from using Spring Cloud Netflix (Eureka) to Spring Cloud Kubernetes as we are running on OpenShift.  Only problem is that KubernetesRegistration.getMetadata() returns null.  This causes a NullPointerException in SpringCloudCommandRouter.updateMembership() when invoked from SpringCloudHttpBackupCommandRouter.updateMembership().

I should add that I'm using Axon v3.3.5 and Spring Cloud Kubernetes v1.0.1.RELEASE.  Also, when I say that KubernetesRegistration.getMetadata() returns null, I mean it is explicitly returning null.  From their github:

```
public class KubernetesRegistration implements Registration, Closeable {
    .
    .
    .
    @Override
    public Map<String, String> getMetadata() {
        return null;
    }
    .
    .
    .
}
```

Any suggestions here?

### PR DESCRIPTION
**Pull request by mtelewicz**
This is a code change to fix issue #9 where Spring Cloud Kubernetes is returning a null map when the SpringCloudCommandRouter requests the metadata for the local service instance.  I've added a simple null check after obtaining the map and, if it is not null, added the load factor, serialized command filter, and serialized command filter class name as before.

This PR resolves #9

### CODE REVIEW

**Comment by abuijze** [comment]
Hi, thanks for reporting this and for providing a PR. Much appreciated.
Would you mind adding a scenario to the test cases to prove this works? Not that we don't trust the implementation, but more to make sure it will not happen ever again....

**Comment by mtelewicz** [comment]
Absolutely.  I'll get on that ASAP.

**Comment by mtelewicz** [comment]
After creating a test where the metadata map is null and seeing the results it seems that this change is a bit more complex than simply checking for null in updateMembership().  The updateMemershipForServiceInstance() method that follows eventually ends up pulling the metadata again to check for the load factor, command filter, and command filter class name in the serviceInstanceMetadataContainsMessageRoutingInformation() method.  I don't fully understand this process where a ConsistentHash is getting updated so I believe a bit more research on my part is needed.

**Comment by mtelewicz** [comment]
I'm definitely lost on this one.  I would appreciate any advice!

**Comment by smcvb** [comment]
Like @abuijze said, thanks for the effort on this @mtelewicz!

From a guidance perspective, I think you need to add a `null` check in the static `serviceInstanceMetadataContainsMessageRoutingInformation(ServiceInstance)`  method and in the `updateMembership(int, CommandMessageFilter)` method. That should be sufficient for ensuring that a `null` entry returned from Spring Cloud Kubernetes `ServiceInstances` is resolved.

That, included with the test cases Allard asks for, should make this PR good to go.

To give you some background: 
The static method is in place as it's also used a configurable filtering solution to remove any `ServiceInstances` which in the absence of the mentioned `Metadata` by definition wouldn't be an Axon node. This static method is referenced in the `SpringCloudCommandRouter.Builder` as the default `serviceInstanceFilter` for the aforementioned purpose.

**Comment by mtelewicz** [comment]
Added a null check to serviceInstanceMetadataContainsMessageRoutingInformation() as @smcvb suggested.  I did try that on my own, but I was concerned that the hash wasn't getting updated as a result.  Perhaps that's the intended outcome, though.  My ignorance of the domain is showing here. :)

File: springcloud/src/test/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouterTest.java [hunk 1]
```diff
@@ -543,13 +559,15 @@ private void initAll(List<SpringCloudCommandRouter> routers) {
...
         when(localServiceInstance.getUri()).thenReturn(URI.create("http://" + host));
-        return SpringCloudCommandRouter.builder()
+        SpringCloudCommandRouter router = SpringCloudCommandRouter.builder()
                                        .discoveryClient(discoveryClient)
                                        .localServiceInstance(localServiceInstance)
                                        .routingStrategy(routingStrategy)
                                        .serviceInstanceFilter(serviceInstance -> true)
                                        .consistentHashChangeListener(consistentHashChangeListener)
                                        .build();
+        //router.updateMembership(LOAD_FACTOR, COMMAND_NAME_FILTER);
```
Comment (smcvb) [inline springcloud/src/test/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouterTest.java]: I don't think this change here is necessary to be honest :-)

File: springcloud/src/test/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouterTest.java [hunk 2]
```diff
@@ -168,6 +168,22 @@ public void testUpdateMembershipUpdatesLocalServiceInstance() {
...
+    
+    @Test
+    public void testUpdateMembershipUpdatesLocalServiceInstanceWhenMetadataNull() {
+        //Mocking null local service instance metadata for this test only
+        when(localServiceInstance.getMetadata()).thenReturn(null);
+        
+        CommandMessageFilter commandNameFilter = new CommandNameFilter(String.class.getName());
+        testSubject.updateMembership(LOAD_FACTOR, commandNameFilter);
+
+        verify(consistentHashChangeListener, never()).onConsistentHashChanged(argThat(item -> item.getMembers()
```
Comment (smcvb) [inline springcloud/src/test/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouterTest.java]: I'd replace this for `verifyZeroInteractions(consistentHashChangeListener);`.

File: springcloud/src/test/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouterTest.java (hunk 1 above)
Comment (mtelewicz) [reply springcloud/src/test/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouterTest.java]: Oops.  Leftover from me messing around.

**Comment by mtelewicz** [comment]
Yes, I am using `SpringCloudHttpBackUpCommandRouter` in my setup.

File: springcloud/src/main/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouter.java [hunk 3]
```diff
@@ -135,9 +135,13 @@ public static Builder builder() {
      */
     public static boolean serviceInstanceMetadataContainsMessageRoutingInformation(ServiceInstance serviceInstance) {
         Map<String, String> serviceInstanceMetadata = serviceInstance.getMetadata();
-        return serviceInstanceMetadata.containsKey(LOAD_FACTOR) &&
-                serviceInstanceMetadata.containsKey(SERIALIZED_COMMAND_FILTER) &&
-                serviceInstanceMetadata.containsKey(SERIALIZED_COMMAND_FILTER_CLASS_NAME);
+        if (serviceInstanceMetadata == null) {
```
[the remark this answers is not in the document]
Comment (mtelewicz) [reply springcloud/src/main/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouter.java]: So shortened.

File: springcloud/src/test/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouterTest.java (hunk 2 above)
Comment (mtelewicz) [reply springcloud/src/test/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouterTest.java]: Done.

**Comment by smcvb** [comment]
Thanks for the effort on this @mtelewicz, I think this should resolve the problem you encountered when utilizing Spring Cloud Kubernetes just fine!
